semgrep/semgrep-interfaces

Semgrep_output_v0.atd, Semgrep_output_v0_j.ml, Semgrep_output_v0_j.mli, semgrep_output_v0.jsonschema, semgrep_output_v0.py, semgrep_output_v0.ts
File, start, and end were marked as optional for error_span, but in reality
they are required by the playground code. This is now reflected in the
interface
=> Update error_span to make required fields required

semgrep_output_v0.atd, semgrep_output_v0.jsonschema, semgrep_output_v0.py, semgrep_output_v0.ts, semgrep_output_v0_j.ml, semgrep_output_v0_j.mli
This is a simplified version of semgrep-core's `Pattern_match.taint_trace` type. It makes a couple of simplifications:
* It omits the sink. The sink is already going to be the primary location of the error message, except for more complicated behavior with DeepSemgrep. We can add it in later if we need to.
* It simplifies the source. The `Call` case is only used for DeepSemgrep, and atdpy does not support recursive types so it would be difficult to represent here anyway. Instead, we can just provide a list of locations.
I believe that despite these simplifications, we will still be able to achieve our goals of providing taint trace information to end users and improving our ability to make PR/MR comments.
This is also meant to be extended to other kinds of dataflow traces (such as …
=> Add taint traces to semgrep output

rule_schema.yaml
This field is pointless unles `strip: true`.
=> metavariable-comparison: Make `metavariable` field optional

semgrep_output_v0.atd, semgrep_output_v0.jsonschema, semgrep_output_v0.py, semgrep_output_v0.ts, semgrep_output_v0_j.ml, semgrep_output_v0_j.mli
This makes a breaking change to the dataflow_trace type, but since it is
not being consumed in production yet, the consensus is that this is
acceptable.
- Combine the multiple taint source tokens into one range spanning the
entire taint source.
- Include `content` for taint source and intermediate vars.
=> Improve dataflow trace output

semgrep_output_v0.atd
This is useful for new parse rate metrics, to prevent accidental
breakage if we add new core error kinds.
Relates to https://github.com/returntocorp/semgrep/pull/5815
=> Update comments for core parse errors

semgrep_output_v0.atd, semgrep_output_v0.jsonschema, semgrep_output_v0.py, semgrep_output_v0.ts, semgrep_output_v0_j.ml, semgrep_output_v0_j.mli
This field was useful back in the day when the semgrep
engine was split between semgrep-core and semgrep-cli.
Now all the logic is in semgrep-core so there is no
need anymore for this unique_id field
test plan:
used in semgrep and everything seems to work fine
=> Remove unique_id from semgrep_output_v0.atd

ast_generic_v0.atd
Swift has some keyword attributes which are not currently in the generic AST, namely `Throws` and `Rethrows`. I decided to just put it in here.
Let me know if that's not something that I should do.
=> feat(swift): added modifiers for Swift

dev.opam
As of 2.10.0, atdpy supports recursive types, which we now use.
Test plan:
```
$ opam install -y --deps-only .
$ make clean && make
```
=> Update required atdpy and atdts version

rule_schema_v1.yaml
This is meant to go along with https://github.com/returntocorp/semgrep/pull/6474. We update the rule schema here to match the corresponding syntax changes.
Make SR lives easier!
Just updated the schema, in hopefully the right way.
I can't add a test in this repo, but this file parses properly:
```
rules:
- id: rule-extensions 
patterns:
- pattern-not: "A"
- pattern-not: 
pattern: "A"
- pattern-inside:
pattern-regex: "B"
- pattern-not-inside:
pattern-not: "C"
message: This rule is just meant to illustrate that we can parse "extensions" to old-grammar rules. 
severity: WARNING
languages: [python]
```
=> feat(schema): update rule schema for syntax extensions

rule_schema_v1.yaml
we fail ungracefully on certain rules, due to a bug in the schema. I think there's actually a bug in the validator. If we check for the presence of a key on something which is not a dictionary (object), Semgrep will die in the CLI
we want to fail gracefully, by having the schema reject the unvalidated rule
I had to change it to first explicitly make it safe that it's an object, and if so, then do the `keys()` check. Otherwise, it will just fail (by reusing the same condition).
I tested this with the `semgrep` snapshots, and it seems good now.
=> fix bug in schema

semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
Added call traces to the output of the Semgrep CLI. This will allow us to output dataflow traces in the JSON, text, and SARIF output from Semgrep CLI
=> refactor dataflow traces

ast_generic_v1.atd
Some languages (JS/TS and Python, that I'm aware of) allow a single import statement to import multiple symbols, e.g. in JS:
```import {x, y} from 'z'```
Currently, we desugar these into multiple imports, but this leads to
strange edge case behavior.
=> Include a list of imports in ImportFrom node

ast_generic_v1_j.ml, semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
Added an `ocaml_max_heap_words` field to the JSON output which denotes the maximum amount of words used by the OCaml process during execution. This will be useful for Metabase scanning, so we can plot this against the repository size and get memory benchmarks over time.
=> feat!: add memory usage

rule_schema_v1.yaml
* Made sure the rules key is now required
* Added some documentation for metavariable-* keys
* Required the languages field be only one we support
I think the required languages field could be done better, such as moving [lang.json](https://github.com/returntocorp/semgrep-app/blob/develop/frontend/src/utils/lang.json) here and autogenerating it, but also that may be overcomplicating something that changes rarely.
=> Require rule key, and specific languages, plus some documentation

rule_schema_v1.yaml
TODO: longer description
This should probably be top level `oneOf`'d with the current schema; we support
backwards compatibility in the core PR
=> feat!: new rule syntax

rule_schema_v1.yaml
forgot `new-source-pattern`, `new-sanitizer-pattern`, and co, which were referenced in the new syntax
=> chore: forgot the new taint stuff

semgrep_output_v1.ts
This fixes two tsc compile-time errors and a confusion with the made-up `Int` type alias, all reported by @ievans. This was fixed in the code generator in https://github.com/ahrefs/atd/pull/325. The TypeScript code `semgrep_output_v1.ts` was generated from that version of atdts, which hasn't been merged or released yet.
=> Regenerate TypeScript from semgrep_output_v1.atd using fixes in atdts

semgrep_output_v1.atd, semgrep_output_v1.ts
I added the annotation needed to read a list of pairs as a TypeScript map.
=> Add ATD annotation needed to use a map rather than an arrays of pairs

semgrep_output_v1.ts
per https://returntocorp.slack.com/archives/C01NXGX2EHZ/p1675454722837449, we need this lint disabled 
should be part of the generation process, @mjambon ?
=> chore: added back eslint and tslint disable

rule_schema_v1.yaml
This PR just makes it so `mode: taint` is not required in new-style taint rules.
=> do not require `mode: taint` in new style taint rule

semgrep_output_v1.atd
This PR includes two sets of changes:
* Use the skip_reason enum instead of `string` for the semgrep CLI API
* Simplify and use optional list fields where we don't need to distinguish a missing/null field from an empty list:
```
~foo: bar list;
```
means the field foo is optional and has an implicit default, which is the empty list. Since we don't need to distinguish an empty list from the absence of a list, this makes the OCaml code simpler. This should also not affect the Python code.
=> Use skip_reason enum instead of string

tests/test-ast
We were using the wrong variable in `make test`, which isn't called by anything at the moment.
This is what happens when `semgrep-core` isn't found in PATH:
```
~/semgrep-interfaces $ make test
make -C tests
make[1]: Entering directory '/home/martin/semgrep-interfaces/tests'
./test-ast
semgrep-core is: 
./test-ast: line 20: semgrep-core: command not found
make[1]: *** [Makefile:4: test] Error 127
make[1]: Leaving directory '/home/martin/semgrep-interfaces/tests'
make: *** [Makefile:48: test] Error 2
```
This is what happens when the environment variable is set incorrectly:
```
$ SEMGREP_CORE=id-dont-exist make test
make -C tests
make[1]: Entering directory '/home/martin/semgrep-interfaces/tests'
./test-ast
semgrep-core is: /home/martin/semgrep/bin/semgrep-core
./test-ast: line 20: …
```
=> Fix error message in 'make test'

Makefile
I didn't run `make` to avoid checking in untested generated code since it's currently out-of-date wrt the atd source.
=> Fix lazy makefile

.github/pull_request_template.md, .gitignore, Language.ml, Language.mli, Makefile, README.md, generate, generate.py, lang.json
Less repositories is better. semgrep-langs was created
before semgrep-interfaces, at a time where we thought
we only needed to share language definitions between
semgrep components.
test plan:
make build
make test
do this or better, merge this whole repo into
[semgrep-interfaces](https://github.com/returntocorp/semgrep-interfaces)).
=> Merge semgrep-langs in semgrep-interfaces

.github/pull_request_template.md, Makefile, dev.opam, semgrep_metrics.atd, semgrep_metrics.py
The atdpy bug was fixed in 2.12.0. I'm not sure how the previous version of this file was created. There's a nonempty diff.
Update: the field `maxMemoryBytes` was using `option` but was not optional. We should not use this. I made the field optional.
This updates the version constraints in `dev.opam` and stresses the importance of running `make setup`.
=> Add semgrep_metrics.py to the auto-generated targets

rule_schema_v1.yaml
Somehow, we changed `strip` to be an array of metavariable names which are meant to be rewritten, in the rule schema for the new syntax. Unfortunately, this is _not at all_ what `Parse_rule` does, so this was just a complete lie by the schema. https://github.com/returntocorp/semgrep/blob/20fa7210ed38eb48dce100687868b1bd1db6f5c4/src/parsing/Parse_rule.ml#L1079
So this just fixes that.
=> fix: change strip type back to bool

semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
The cai_ids have not been used for quite some time. I am trying to finish removing them from the app and CLI to simplify the logic in both.
See https://github.com/returntocorp/semgrep-app/pull/8773
=> chore: make cai_ids optonal list

semgrep_metrics.atd, semgrep_metrics.py, semgrep_output_v1_j.ml
test plan:
make test in semgrep works better.
=> add nullable to ci and projecthash in semgrep_metrics.py

rule_schema_v1.yaml
This PR just changes the `focus` operator's type in the rule schema to reflect @enncoded's excellent work!
=> fix: `focus` operator type

semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
This should be an string enum rather than some int representation that approximates it.
To migrate we need the typing to allow for both string and int, which we can do by pushing the typing up a layer until the CLI versions using int are deprecated.
Closes APP-4267
=> enable the migration of severity from int to string

semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
This is needed so we can start strongly typing the messages between the CLI and semgrep.dev.
=> update api_scans_findings to match current usage

semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
For context, [this PR](https://github.com/returntocorp/semgrep/pull/7892) was created a while back to get the "contributions" in a CI scan and upload with the findings/ignores, but it was implemented in python.
I'm translating that logic to semgrep-core so it will be available to both pysemgrep and osemgrep.
=> chore: Add contribution model

semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
The contributions type was created as a struct so the output would be in the form of 
```
{
"contributions": [
{
"commit_hash": "9044690c5c36e9228432e1d32b9bff4938338cc8",
"commit_timestamp": "2023-06-07 22:39:48 -0400",
"contributor": {
"commit_author_name": "Zach Yannes",
"commit_author_email": "zach@semgrep.com"
}
},
{
"commit_hash": "bb28428c27f34a7ff332f61936c6793be2b8a038",
"commit_timestamp": "2022-11-08 15:00:56 -0500",
"contributor": {
"commit_author_name": "Zach Yannes",
"commit_author_email": "zach@returntocorp.com"
}
},
{
"commit_hash": "1d8f8bb1ff3214016f016dc5c439d83c4ffe04c0",
"commit_timestamp": "2022-09-19 10:42:57 -0400",
"contributor": {
"commit_author_name": "Zach Yannes",
"commit_author_email": "zach@returntocorp.com"
}
},
{
"commit_hash": …
```
=> fix: Change contributions type from struct to list

semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
Updated the `FoundDependency` class to now store a list of `Child` objects which contain the name and package of the dependencies they rely on. Will be used in the App to construct the adjacency list
=> Semgrep Interface Changes for Path to Transitivity (CLI)

semgrep_output_v1.atd, semgrep_output_v1.jsonschema, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
All the optional fields are new since `0.123.0`
0.123.0 data: https://github.com/returntocorp/semgrep/blob/084ff5f16866ab66337655dbc06672e05d3089dc/cli/src/semgrep/app/scans.py#L301
Current data: https://github.com/returntocorp/semgrep/blob/develop/cli/src/semgrep/app/scans.py#L320
=> Add type for `/complete` data

rule_schema_v1.yaml
Supports ability to have HTTP request changed to, for instance, add authorization headers which depend on message content and metavariables.
=> feat(secrets): add auth object to request

semgrep_output_v1.atd
=> update comment for ci_scan_complete.dependencies

semgrep_output_v1.atd, semgrep_output_v1_j.ml
=> use string wrap for fpath (part 3)

semgrep_output_v1.atd, semgrep_output_v1_j.ml
=> string wrap part4, ruleid

semgrep_metrics.atd, semgrep_metrics.py
=> add diff scan related metrics

semgrep_studio_v1.proto
This was in a branch but not in main
test plan:
see related PR in semgrep-server
=> Use the latest semgrep_studio_v1.proto

.github/workflows/lint.yaml, scripts/check-backwards-compatability.sh, semgrep_output_v1.atd
This adds the very first iteration of a linter that uses atd diff to check backwards compatibility against all supported CLI versions.
=> Add CI workflow to test backwards compatability

.github/workflows/lint.yaml, semgrep_output_v1.atd, semgrep_output_v1.py
The default var in python land needs the class to wrap the string.
Typescript is fine because everything is a string there anyway.
Also adding mypy to the checks to catch this kind of thing.
=> fix python default var and add mypy linting

rule_schema_v1.yaml
=> chore: fix typo

rule_schema_v2.atd, semgrep_metrics.atd, semgrep_output_v1.atd
=> Switch to ATD_string_wrap

semgrep_output_v1.atd, semgrep_output_v1.py, semgrep_output_v1.ts, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
=> Rename SpecifiedParseError to OtherParseError

rule_schema_v1.yaml
=> add multi-type syntax to metavariable-type rule

rule_schema_v2.atd, rule_schema_v2_adapter.ml
It can now parse many rules, even though the where
part is unfinished
test plan:
=> Improvement to rule_schema_v2.atd

rule_schema_v1.yaml, rule_schema_v2.atd, rule_schema_v2_adapter.ml
This better match the syntax.
The goal is not to redo Rule.ml and have clean variant types!
The goal is to specify the syntax.
test plan:
=> Simplify rule_schema_v2.atd, use less variant

rule_schema_v1.yaml, rule_schema_v2.atd, rule_schema_v2_adapter.ml
This is actually more precise than rule_schema_v1.yaml!
test plan:
=> Specify taint syntax in rule_syntax_v2.atd

rule_schema_v2.atd, rule_schema_v2_adapter.ml
test plan:
see related semgrep PR
=> Specify SSC in rule_schema_v2.atd

.codemapignore, rule_schema_v2.atd, semgrep_output_v1.atd
=> Small cleanup to rule_schema_v2.atd and .codemapignore

rule_schema_v2.atd
=> Add steps: in rule_schema_v2.atd and select:

semgrep_metrics.atd, semgrep_metrics.py
Creates a new metrics type which is closely aligned with osemgrep's Engine_type.t which allows for more precise tracking of the engine feature matrix. This is needed compared to a simple enumeration since we have more orthogonal features than previously. For instance, we can now perform analysis on at least two axes (within pro):
(1) secrets valdiation [enabled <-> disabled];
(2) dataflow [none <-> ... <-> interfile]
Creating a new enum entry for each possible permutation is not futureproof (and is ugly), so we need a more complex type here.
=> feat: more granular pro engine config metrics

semgrep_metrics.atd, semgrep_metrics.py
See https://semgrepinc.slack.com/archives/C01NXGX2EHZ/p1703115761745179
=> fix: mypy issues after #202

.github/workflows/lint.yaml, scripts/check-backwards-compatibility
This is the same set of changes as #207 but I pushed this branch to the original repo owned by semgrep instead of my personal fork. The CI checks should now all pass.
=> [copy of] Tentative fixes for the atddiff check #207

semgrep_metrics.atd, semgrep_metrics.py
Helps PA-3312.
This breakdown will allow us to calculate the number of findings per bytes of code scanned per product to understand users better.
=> feat(metrics): add findings by product breakdown

ast_generic_v1.atd, ast_generic_v1_j.ml
=> Rename PatUnderscore to PatWildcard

Language.ml, generate.py, lang.json
=> chore: tag Elixir as a pro language

rule_schema_v1.yaml
Removes the `mode` setting for the old postprocessor syntax we replaced 3-4 months ago. This syntax is undocumented and unused internally; externally it was never part of a documented public API.
BREAKING CHANGE: This means we may now reject rules with `mode: semgrep_internal_postprocessor`
=> feat!: remove deprecated postprocessor syntax

semgrep_metrics.atd, semgrep_metrics.py
See: https://github.com/semgrep/semgrep/pull/9670
=> add: os and isjs environment metrics

semgrep_output_v1.atd, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
These types need `show` and `eq` instances for: https://github.com/semgrep/semgrep/pull/9695
=> Derive show and eq for some supply chain types

.gitignore
=> chore: Ignore vim swap files

semgrep_metrics.atd, semgrep_metrics.py
This is needed since we are updating the way the origin based filtering for validation works, and changing it from a whitelist of [pro_rules] to a blacklist of [community], i.e., effectively, [pro_rules, custom, None].
=> feat(secrets): new origin policy for not community

semgrep_metrics.atd
test plan:
make
make in semgrep
=> Add comment about the use of mutable in semgrep_metrics.atd

semgrep_metrics.atd
=> Add TODO comments in semgrep_metrics.atd

semgrep_metrics.atd, semgrep_metrics.py
=> Adding a new metric for the number of scanned diff targets in inter-file diff scan mode

rule_schema_v2.atd
This PR makes it so that the per-pattern fixes, introduced in https://github.com/semgrep/semgrep-proprietary/pull/1541/files, are now specified in the rule schema.
=> feat(rules): update rule schema atd for fix

rule_schema_v2.atd
This PR adds a new rule option `nonkeyword_attributes_order_matters`, which allows users to make decorator/ non-keyword attributes matching stricter, to the rule schema atd file. The default matching for attributes is order-agnostic, but if this rule option is set to `true`, non-keyword attributes (e.g. decorators in Python) will be matched in order, while keyword attributes (e.g. static, inline, etc) are not affected.
=> feat: add nonkeyword_attributes_order_matters rule option in rule schema atd

rule_schema_v2.atd
This PR updates the name of the option added in #255. The team decided that `decorators_order_matters` is better than `nonkeyword_attributes_order_matters` after discussion as the new name is clearer to users.
=> fix: update name of decorator rule option in rule schema atd

Language.ml, Language.mli, generate.py, lang.json
Support for Move language on Aptos
---
=> feat: add support for move on aptos

semgrep_metrics.atd, semgrep_metrics.py
We want to start including the deployment id when reporting metrics. This will be especially helpful for extensions, as then we can track # of logged in users by deployment
=> include deployment id

semgrep_metrics.atd
=> fix: mark deployment id as mutable

semgrep_metrics.atd, semgrep_metrics.py
=> Add comments in semgrep_metrics.atd about clientIp and userAgent

semgrep_metrics.atd, semgrep_metrics.py
Record how many autofix and ignores have been triggered via IDE since users have asked for this
=> add autofix and ignore fields

rule_schema_v2.atd
This PR just adds the `as` field to formulae, due to the addition of embedding matches into arbitrary metavariables.
https://github.com/semgrep/semgrep-proprietary/pull/1730
=> feat: as-metavariable

Language.ml, Language.mli, generate.py, lang.json
=> Circom language support

semgrep_metrics.atd
=> Add comments in semgrep_metrics.atd

rule_schema_v1.yaml, rule_schema_v2.atd
=> add semgrep-internal-metavariable-name to rule schema

ast_generic_v1_j.ml
Looks like `make` wasn't run in https://github.com/semgrep/semgrep-interfaces/pull/279
=> chore: regenerate for #279

rule_schema_v1.yaml, rule_schema_v2.atd
=> feat: add module as possible key

rule_schema_v2.atd
=> fix: rename field for compatibility

rule_schema_v1.yaml
=> fix: update required props for metavariable-name

Language.ml, Language.mli, generate.py, lang.json
- [X ] I ran `make setup && make` to update the generated code after editing a `.atd` file (TODO: have a CI check)
- [X ] I made sure we're still backward compatible with old versions of the CLI.
See https://atd.readthedocs.io/en/latest/atdgen-tutorial.html#smooth-protocol-upgrades 
I assume that adding a new language is backwards compatiable?
=> Adding Move on Sui to languages

semgrep_output_v1.atd, semgrep_output_v1.py
Manifest kind needs to be hashable to be used in a `set()`. This PR adds the `@dataclass(frozen=true)` decorator to it.
=> chore(lockfileless): Made manifest kind hashable

semgrep_output_v1.atd, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
In order to consolidate the `manifest_kind` type in interfaces with `Manifest_kind.ml`, this PR:
- transfers the comments from the ML file to interfaces
- adds `eq`, `show`, and `yojson` derivations to the ATD definition
=> chore(sca): add comments to manifest kinds

semgrep_output_v1.atd
=> Comments on minimum cli version and on gated logged in fields

semgrep_metrics.atd, semgrep_metrics.py
Not used anymore.
test plan:
make in semgrep
=> Remove the osemgrep sarif metrics

semgrep_output_v1.atd, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
=> Remove some useless deriving yojson

semgrep_output_v1.atd
Just fixed a typo, the return value is not an error message, it only returns in the success case. It's a success message.
=> fix: erroneous comment in interface

LICENSE, NOTICE, README.md
We previously did not distribute a specific license file with this repository since it is included in semgrep/semgrep as a submodule, but for clarity as to how this specific set of files is licensed (and because users may obtain them separately) let's add a copy of the license here.
Closes https://github.com/semgrep/semgrep/issues/10850.
=> chore: add LICENSE

rule_schema_v1.yaml, rule_schema_v2.atd
Allows metavariable-name to appear without a semgrep-internal prefix when using the modules constraint (but not yet for kind).
=> feat: expose metavariable-name.modules

rule_schema_v1.yaml
pattern-sinks:
- patterns:
- pattern: $OBJ.foo($SINK, $ARG1)
- focus-metavariable: $SINK
requires:
- $SINK: TAINT
- $OBJ: OBJ
- $ARG1: ARG1
Required-by: semgrep/semgrep-proprietary#3414
=> rule_schema_v1: taint: Add multi-requires

semgrep_output_v1.atd, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
=> feat(sca): Add deriving show, eq to tr_cache_key

semgrep_output_v1.atd, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
=> add deriving eq to rule_id

rule_schema_v1.yaml, rule_schema_v2.atd
=> add `fqn` and `fqns` to rule schema

.github/pull_request_template.md
Adds another checkbox to remind people to ensure that their accompanying semgrep-pro PRs are ready to merge before merging the semgrep-interfaces PR. This will hopefully help avoid situations where later changes to semgrep-interfaces cannot be used in semgrep-pro.
=> chore: add checkbox for pro PR to PR checklist

semgrep_output_v1.atd, semgrep_output_v1_j.ml, semgrep_output_v1_j.mli
This adds a lot of ppx_deriving.ord annotations allowing us to sort results deterministically as opposed to the lazy approach where we'd omit fields when sorting a list of results.
No types have changed.
=> Add instructions to derive comparison functions for sorting purposes

semgrep_metrics.atd, semgrep_metrics.py
For example, the Semgrep backend need to still be able to _consume_data
=> feat: add metrics for mcp rpc calls to semgrep

Language.ml, Language.mli, generate.py, lang.json, rule_schema_v1.yaml
=> feat: add Gosu language with develop maturity
