semgrep/semgrep-interfaces

Semgrep_output_v0.atd
Semgrep_output_v0_j.ml
Semgrep_output_v0_j.mli
semgrep_output_v0.jsonschema
semgrep_output_v0.py
semgrep_output_v0.ts

See https://github.com/returntocorp/semgrep/pull/5385

add: Include SCA info in semgrep-app findings output

---

Semgrep_output_v0.atd
Semgrep_output_v0_j.ml
Semgrep_output_v0_j.mli
semgrep_output_v0.jsonschema
semgrep_output_v0.py
semgrep_output_v0.ts

Reverts returntocorp/semgrep-interfaces#3

Revert "add: Include SCA info in semgrep-app findings output"

---

semgrep_output_v0.atd
semgrep_output_v0.py
semgrep_output_v0.ts
semgrep_output_v0_j.ml
semgrep_output_v0_j.mli

Adds a derive for `show` so you can print debug the types defined here.

Add `deriving show` for OCaml type definitions

---

README.md
rule_schema.yaml

This eliminates the need for separate PRs to update the version of this
file in Semgrep and Semgrep App.

Move rule schema to semgrep_interfaces

---

semgrep_output_v0.atd

See comment here:
https://github.com/returntocorp/semgrep-interfaces/pull/17#discussion_r931920013

Add additional coupling tag to comment

---

semgrep_output_v0.atd
semgrep_output_v0.jsonschema
semgrep_output_v0.py
semgrep_output_v0.ts
semgrep_output_v0_j.ml
semgrep_output_v0_j.mli

This PR defines a typed interface for supply chain findings.

feat: Typed Supply Chain Info

---

semgrep_output_v0.atd
semgrep_output_v0_j.ml
semgrep_output_v0_j.mli

For https://github.com/returntocorp/semgrep/pull/5916, after adding an `Inside` pattern for formulas.

add inside pattern

---

semgrep_output_v0.atd
semgrep_output_v0.jsonschema
semgrep_output_v0.py
semgrep_output_v0.ts
semgrep_output_v0_j.ml
semgrep_output_v0_j.mli

https://github.com/returntocorp/semgrep/pull/6049
Includes extra stuff because only the ocaml files got re-generated on https://github.com/returntocorp/semgrep-interfaces/pull/25

feat: Add transitivity info to supply chain findings

---

semgrep_output_v0.atd
semgrep_output_v0.jsonschema
semgrep_output_v0.py
semgrep_output_v0.ts
semgrep_output_v0_j.ml
semgrep_output_v0_j.mli

https://github.com/returntocorp/semgrep/pull/6092

feat: Add optional line number info to supply chain findings

---

semgrep_output_v0.atd
semgrep_output_v0.jsonschema
semgrep_output_v0.py
semgrep_output_v0.ts
semgrep_output_v0_j.ml
semgrep_output_v0_j.mli

This will allow semgrep-core to compute fixes for the CLI to apply.

Add rendered_fix to core_match_extra

---

rule_schema.yaml

In accordance with https://github.com/returntocorp/semgrep/pull/6105

Updated the schema for `focus-metavariable`

---

semgrep_output_v0.atd
semgrep_output_v0.jsonschema
semgrep_output_v0.py
semgrep_output_v0.ts
semgrep_output_v0_j.ml

see: https://github.com/returntocorp/semgrep/pull/6297

fix: Remove gradle as a separate ecosystem

---

rule_schema_v1.yaml

This is in preparation for semgrep 1.0.0 release
test plan:
see related PR in semgrep (and semgrep-app later)

rename rule_schema.yml to rule_schema_v1.yml

---

ast_generic_v1.atd
rule_schema_v1.yaml
semgrep_output_v1.atd
semgrep_output_v1.jsonschema
semgrep_output_v1.py
semgrep_output_v1.ts
semgrep_output_v1_j.ml
semgrep_output_v1_j.mli

Adding the EXPERIMENTAL tags to the .atd and jsonschema for 1.0

---

ast_generic_v1.atd
ast_generic_v1_j.ml
ast_generic_v1_j.mli

As part of v1 we can fix all the raise Todo in ast_generic_to_v1
by adding constructs that was added in the last few months.
test plan:
make in semgrep

AST_generic_v1: update to current AST_generic.ml

---

rule_schema_v1.yaml

Made a typo, this should have been anyOf (either), instead of oneOf (fails if both match, and breaks semgrep tests)

oneOf should have been anyOf :(

---

rule_schema_v1.yaml

This is part of a pull request modifying several repositories:
- https://github.com/returntocorp/semgrep/pull/6797
- https://github.com/returntocorp/semgrep-langs/pull/24
- https://github.com/returntocorp/semgrep-interfaces/pull/46
- https://github.com/returntocorp/semgrep-docs/pull/843

json flag added to the schema for extracting json content

---

semgrep_output_v1.ts

See https://github.com/ahrefs/atd/pull/328

Updated generated TypeScript code to disable eslint reporting

---

semgrep_output_v1.atd
semgrep_output_v1.jsonschema
semgrep_output_v1.py
semgrep_output_v1.ts
semgrep_output_v1_j.ml
semgrep_output_v1_j.mli

This will help us keep track of which errors are raised by pro engine users that prevent pro analysis from happening.

Add errors specifically for oom and timeout during preprocessing

---

semgrep_output_v1.atd
semgrep_output_v1.jsonschema
semgrep_output_v1.py
semgrep_output_v1.ts
semgrep_output_v1_j.ml
semgrep_output_v1_j.mli

chore: label pro matches with engine kind

---

rule_schema_v1.yaml

Updated the rule schema for the new taint syntax.

feat!: schema for new taint

---

rule_schema_v1.yaml

Based on current data we only have 8 rules in registry that would fail this validation here and only one customer has rules that fail the validation in their configuration who I will work with to get their config sorted out.

validate "id"

---

README.md

chore: update readme instructions

---

Language.ml
Language.mli
generate.py
lang.json

This will help https://github.com/returntocorp/semgrep/issues/8088
test plan:
make

Adding protocol buffer to Language.ml

---

rule_schema_v1.yaml

add metavariable-type to schema

---

lang.json

Not sure if I need to run something after updating this

Add .h for c & c++

---

rule_schema_v1.yaml

add metavariable-type syntax to rule 2.0

---

semgrep_output_v1.atd
semgrep_output_v1.jsonschema
semgrep_output_v1.py
semgrep_output_v1.ts
semgrep_output_v1_j.ml
semgrep_output_v1_j.mli

Rename `api_scans_findings` to `ci_scan_results`

---

rule_schema_v1.yaml

feat!(...): update schema

---

rule_schema_v1.yaml

feat(...): extend rule schema for internal post-processor

---

semgrep_studio_v1.proto

add semgrep_studio_v1

---

rule_schema_v1.yaml
semgrep_output_v1.atd
semgrep_output_v1.jsonschema
semgrep_output_v1.py
semgrep_output_v1.ts
semgrep_output_v1_j.ml
semgrep_output_v1_j.mli

Related:
[semgrep-pro PR](https://github.com/returntocorp/semgrep-proprietary/pull/922)
[semgrep PR](https://github.com/returntocorp/semgrep-interfaces/pull/111)

feat: unverified secrets

---

semgrep_output_v1.atd
semgrep_output_v1.py

They do not seem needed
test plan:

remove python decator with frozen=True

---

semgrep_metrics.atd

comment in semgrep_metrics.atd

---

rule_schema_v1.yaml

allow additional properties

---

semgrep_runner_v1.proto

chore: Add runner protos

---

.github/workflows/lint.yaml

We want this comment to be left whenever the previous step ran (even if it was a failure)

Always leave backwards compatibility comment
